# Generated by Django 6.0.6 on 2026-06-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedeal',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
