# Generated by Django 5.0.4 on 2026-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedeal',
            name='from_provider_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedeal',
            name='to_provider_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
