# Generated by Django 6.0.6 on 2026-06-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_add_discount_percentage'),
        ('collaborations', '0002_add_provider_confirmations'),
    ]

    operations = [
    ]
