# Generated by Django 6.0.6 on 2026-06-18 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perkimage',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.perk'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='catalog.perk'),
        ),
    ]
