# Generated by Django 6.0.6 on 2026-06-18 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('life_moments', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carepackage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_care_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carepackage',
            name='perks',
            field=models.ManyToManyField(blank=True, to='catalog.perk'),
        ),
        migrations.AddField(
            model_name='creditdonation',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='creditdonation',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditdonation',
            name='life_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='life_moments.lifeevent'),
        ),
        migrations.AddField(
            model_name='carepackage',
            name='life_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_package', to='life_moments.lifeevent'),
        ),
    ]
