# Generated by Django 6.0.6 on 2026-06-18 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('catalog', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleassignment',
            name='assigned_to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='assigned_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_assignments', to='companies.team'),
        ),
        migrations.AddField(
            model_name='perkbundle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='companies.company'),
        ),
        migrations.AddField(
            model_name='perkbundle',
            name='perks',
            field=models.ManyToManyField(blank=True, to='catalog.perk'),
        ),
        migrations.AddField(
            model_name='bundleassignment',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='approvals.perkbundle'),
        ),
        migrations.AddField(
            model_name='perkrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perk_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perkrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
