# Generated by Django 6.0.6 on 2026-06-20 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santaassignment',
            name='gifted_perk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santa_gifts', to='catalog.perk'),
        ),
    ]
