# Generated by Django 5.0.4 on 2026-06-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_group_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
