# Generated by Django 6.0.6 on 2026-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_add_win_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeentry',
            name='submission',
            field=models.TextField(),
        ),
    ]
