# Generated by Django 6.0.6 on 2026-06-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='reply_context',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
