# Generated by Django 6.0.6 on 2026-06-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='reputation_tier',
            field=models.CharField(default='unranked', max_length=20),
        ),
    ]
