# Generated by Django 6.0.6 on 2026-06-21 00:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=users.models.generate_referral_code, max_length=8, unique=True),
        ),
    ]
