# Generated by Django 5.0.4 on 2026-06-20 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('expired', 'Expired')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_buys', to=settings.AUTH_USER_MODEL)),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buys', to='catalog.perk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBuyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_in', models.BooleanField(default=False)),
                ('locked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='group_buying.groupbuy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group_buy', 'user')},
            },
        ),
    ]
